// TODO 导出组件 在Index.ets导出文件中声明
export { StaticMainPage } from './src/main/ets/components/StaticMainPage'

export { StaticInnerPage } from './src/main/ets/pages/StaticInnerPage'

// TODO 导出类 在Index.ets导出文件中声明
export { Log } from './src/main/ets/utils/Log'

export { InitCommon } from './src/main/ets/InitCommon'

export { HiLog } from './src/main/ets/utils/HiLog'

export { RouterHelper } from './src/main/ets/utils/RouterHelper'

export { ToastUtil } from './src/main/ets/utils/ToastUtil'

// TODO 导出函数 在Index.ets导出文件中声明
export { func, func2 } from './src/main/ets/utils/Log'
