export let PAGE_START = "pages/StartPage";
export let PAGE_START_OTHER = "pages/other/OtherStartPage";
export let PAGE_RELATIVE = "pages/entry/basepage/RelativePage";
export let PAGE_INPUT = "pages/entry/basepage/InputPage";
export let PAGE_COLUMN = "pages/entry/basepage/ColumnPage";
export let PAGE_IMAGE = "pages/entry/basepage/ImagePage";
export let PAGE_WANT_ABILITY = "pages/entry/want/WantAbilityPage";

export let PAGE_EVENT = "pages/entry/event/EventPagePage";
export let PAGE_NAPI = "pages/entry/napi/NApiPage";

export let PAGE_HTTPS_CERT_PIN = "pages/entry/http/HttpsCertPinPage";
export let PAGE_HTTPS = "pages/entry/http/HttpsPage";
export let PAGE_WEBSOCKETS = "pages/entry/http/WebsocketsPage";

export let PAGE_SP = "pages/entry/sp/SPPage";
export let PAGE_KEY_VALUE = "pages/entry/sp/KeyValuePage";

export let PAGE_FILE = "pages/entry/file/FilePage";
export let PAGE_UTD = "pages/entry/file/UTDPage";

export let PAGE_DATABASE = "pages/entry/database/DatabasePage";

export let PAGE_COMPONENT_STATUS = "pages/entry/status/ComponentPage";
export let PAGE_STATE = "pages/entry/status/state/StatePage";
export let PAGE_STATE_CHANGED_1 = "pages/entry/status/state/StateChangedPage1";
export let PAGE_STATE_CHANGED_2 = "pages/entry/status/state/StateChangedPage2";
export let PAGE_STATE_CHANGED_3 = "pages/entry/status/state/StateChangedPage3";
export let PAGE_STATE_CHANGED_4 = "pages/entry/status/state/StateChangedPage4";
export let PAGE_STATE_CHANGED_5 = "pages/entry/status/state/StateChangedPage5";
export let PAGE_PROP_CHANGED_1 = "pages/entry/status/prop/PropPage1";
export let PAGE_PROP_CHANGED_2 = "pages/entry/status/prop/PropPage2";
export let PAGE_LINK = "pages/entry/status/link/LinkPage";
export let PAGE_PROVIDE_CONSUME = "pages/entry/status/provide/ProvideConsumePage";
export let PAGE_PROVIDE_CONSUME_2 = "pages/entry/status/provide/ProvideConsumePage2";
export let PAGE_PROVIDE_CONSUME_3 = "pages/entry/status/provide/ProvideConsumePage3";
export let PAGE_OBSERVED_CLASS_PAGE = "pages/entry/status/observed/ObservedClassPage";
export let PAGE_OBSERVED_CLASS_PAGE_2 = "pages/entry/status/observed/ObservedClassPage2";
export let PAGE_OBSERVED_ARRAY_PAGE = "pages/entry/status/observed/ObservedArrayPage";
export let PAGE_OBSERVED_ARRAY_PAGE_2 = "pages/entry/status/observed/ObservedArrayPage2";

export let PAGE_LOCAL_STORAGE_PAGE_1 = "pages/entry/status/localstorage/LocalStoragePage1";
export let PAGE_LOCAL_STORAGE_PAGE_2 = "pages/entry/status/localstorage/LocalStoragePage2";
export let PAGE_LOCAL_STORAGE_PAGE_3 = "pages/entry/status/localstorage/LocalStoragePage3";
export let PAGE_LOCAL_STORAGE_PAGE_4 = "pages/entry/status/localstorage/LocalStoragePage4";
export let PAGE_LOCAL_STORAGE_PAGE_5 = "pages/entry/status/localstorage/LocalStoragePage5";

export let PAGE_APP_STORAGE_PAGE_1 = "pages/entry/status/appstorage/AppStoragePage1";
export let PAGE_EMIT_PAGE = "pages/entry/status/emit/EmitPage";
export let PAGE_PERSISTENT_PAGE = "pages/entry/status/persistent/PersistentPage";
export let PAGE_ENVIRONMENT_PAGE = "pages/entry/status/environment/EnvironmentPage";
export let PAGE_WATCH_PAGE = "pages/entry/status/watch/WatchPage";
export let PAGE_WATCH_LINK_PAGE = "pages/entry/status/watch/WatchLinkPage";
export let PAGE_WATCH_CHANGE_TIME_PAGE = "pages/entry/status/watch/WatchChangeTimePage";
export let PAGE_$$_PAGE = "pages/entry/status/$$/DollarDollarPage";
export let PAGE_TRACK_PAGE = "pages/entry/status/track/TrackPage";

export let PAGE_FREEZE_PAGE_1 = "pages/entry/freeze/FreezePage1";
export let PAGE_FREEZE_PAGE_2 = "pages/entry/freeze/FreezePage2";
export let PAGE_FREEZE_TAB = "pages/entry/freeze/TabFreezePage";
export let PAGE_FREEZE_LIST = "pages/entry/freeze/ListFreezePage";
export let PAGE_FREEZE_NAVIGATION = "pages/entry/freeze/NavigationFreezePage";

export let PAGE_PROMISE_ASYNC_WAIT = "pages/entry/promise/PromiseAsyncWaitPage";
export let PAGE_TASK_POOL = "pages/entry/thread/TaskPoolPage";
export let PAGE_WORKER = "pages/entry/thread/WorkerPage";

export let PAGE_STATIC_LIBRARY = "pages/entry/har_hsp/StaticLibraryPage";
export let PAGE_STATIC_INNER = "pages/static/common/StaticInnerPage";
export let PAGE_STATIC_CAMERA = "pages/static/camera/CameraEntryPage";

export let PAGE_SHARED_LIBRARY = "pages/entry/har_hsp/SharedLibraryPage";
export let PAGE_SHARED_INNER = "pages/shared/context/SharedInnerPage";

export let PAGE_MVVM_TEST = "pages/mvvm/TodoListPage";
export let PAGE_TEST_LIST = "pages/entry/list/ListA1";
export let PAGE_ARTICLE_LIST = "pages/entry/list/ArticleListPage";

export let PAGE_RENDER_IF_ELSE = "pages/entry/render_control/If_ElsePage";
export let PAGE_RENDER_IF_ELSE_WITH_STATE = "pages/entry/render_control/If_Else_WithStatePage";
export let PAGE_RENDER_IF_ELSE_WITH_STATE_CHANGED = "pages/entry/render_control/If_Else_WithStateChangedPage";
export let PAGE_RENDER_FOR_EACH_PAGE_1 = "pages/entry/render_control/ForEachPage";
export let PAGE_RENDER_LAZY_FOR_EACH_PAGE_1 = "pages/entry/render_control/LazyForEachPage";
export let PAGE_RENDER_LAZY_FOR_EACH_PAGE_2 = "pages/entry/render_control/LazyForEachClassPage";
export let PAGE_RENDER_LAZY_FOR_EACH_PAGE_3 = "pages/entry/render_control/LazyForEachReusablePage";

export let PAGE_BUILDER_1 = "pages/entry/custom/BuilderPage";
export let PAGE_BUILDER_2 = "pages/entry/custom/CustomBuilderPage";
export let PAGE_BUILDER_3 = "pages/entry/custom/MultiBuildersPage";
export let PAGE_LOCAL_BUILDER_1 = "pages/entry/custom/LocalBuilderPage";

export let PAGE_ANIMATE_TO = "pages/animate/AnimateToPage";

