export let PAGE_START = "pages/entry/StartPage";
export let PAGE_RELATIVE = "pages/entry/RelativePage";
export let PAGE_INPUT = "pages/entry/InputPage";
export let PAGE_COLUMN = "pages/entry/ColumnPage";
export let PAGE_IMAGE = "pages/entry/ImagePage";
export let PAGE_HTTPS_CERT_PIN = "pages/entry/HttpsCertPinPage";
export let PAGE_HTTPS = "pages/entry/HttpsPage";
export let PAGE_WEBSOCKETS = "pages/entry/WebsocketsPage";
export let PAGE_FILE = "pages/entry/FilePage";

export let PAGE_STATIC_LIBRARY = "pages/entry/StaticLibraryPage";
export let PAGE_STATIC_INNER = "pages/static/common/StaticInnerPage";

export let PAGE_SHARED_LIBRARY = "pages/entry/SharedLibraryPage";
export let PAGE_SHARED_INNER = "pages/shared/context/SharedInnerPage";

export let PAGE_CAMERA_STATIC = "pages/static/camera/CameraEntryPage";
